version: "3.5"
services:
  # mysql:
  #   image: mysql:8
  #   command: --default-authentication-plugin=mysql_native_password
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_DATABASE: hello
  #   ports:
  #     - 3306:3306
  #   volumes:
  #     - /var/lib/mysql:/var/lib/mysql
  #   networks:
  #     - api
  node_api:
    image: xmatheuslopes/node-api:0.0.4
    ports:
      - 8081:8081
    volumes:
      - ./src:/app/src
    # depends_on:
    #   - mysql
    networks:
      - api
    command: bash -c "npm run dev"
networks:
  api:
    driver: bridge
