apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      serviceAccountName: jenkins
      securityContext:
        runAsUser: 0
      containers:
      - name: jenkins
        image: xmatheuslopes/jenkins:0.0.1
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: jenkins-home
          mountPath: /var/jenkins_home
        - name: dockersock
          mountPath: "/var/run/docker.sock"
      volumes:
      - name: jenkins-home
        hostPath:
          path: /var/jenkins_home
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock  
